server:
  port: 8086
  servlet:
    context-path:

spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

# 设置mybatis的别名(指定包下的类名即别名)
mybatis:
  type-aliases-package: com.springboot.domain
  mapper-locations: mybatis/mapper/*.xml
